
# NOTE: Python has no constants, so just treat these things as constants

# Board
BOARD_SIZE = 8
BOARD_SQUARES = BOARD_SIZE * BOARD_SIZE
FILE_COUNT = BOARD_SIZE
RANK_COUNT = BOARD_SIZE

# Colors
WHITE = 0
BLACK = 1
NO_COLOR = -1

# Piece types
PAWN = 0
KNIGHT = 1
BISHOP = 2
ROOK = 3
QUEEN = 4
KING = 5
NO_PIECE_TYPE = -1

# Pieces (color * 6 + type)
NO_PIECE = -1
W_PAWN = WHITE * 6 + PAWN
W_KNIGHT = WHITE * 6 + KNIGHT
W_BISHOP = WHITE * 6 + BISHOP
W_ROOK = WHITE * 6 + ROOK
W_QUEEN = WHITE * 6 + QUEEN
W_KING = WHITE * 6 + KING
B_PAWN = BLACK * 6 + PAWN
B_KNIGHT = BLACK * 6 + KNIGHT
B_BISHOP = BLACK * 6 + BISHOP
B_ROOK = BLACK * 6 + ROOK
B_QUEEN = BLACK * 6 + QUEEN
B_KING = BLACK * 6 + KING

PIECE_COUNT = B_KING + 1

# Castling rights bitmask
CASTLING_NONE = 0
CASTLING_WHITE_KING = 1 << 0
CASTLING_WHITE_QUEEN = 1 << 1
CASTLING_BLACK_KING = 1 << 2
CASTLING_BLACK_QUEEN = 1 << 3
CASTLING_ALL = (
    CASTLING_WHITE_KING
    | CASTLING_WHITE_QUEEN
    | CASTLING_BLACK_KING
    | CASTLING_BLACK_QUEEN
)

# En passant
NO_EP_FILE = -1

# Move flags bitmask
MOVE_FLAG_QUIET = 0
MOVE_FLAG_CAPTURE = 1 << 0
MOVE_FLAG_EN_PASSANT = 1 << 1
MOVE_FLAG_CASTLE = 1 << 2
MOVE_FLAG_PROMOTION = 1 << 3
MOVE_FLAG_DOUBLE_PAWN_PUSH = 1 << 4

STARTING_POSITION_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"

